### ISSUE TITLE
php 5.6 support

### ISSUE THREAD

**Issue by tomadmiraal** [spatie/laravel-varnish#13]
I would love to use this varnish package on laravel but we are still using php 5.6. while installing the package I receive the following error:

Could not find package spatie/laravel-varnish at any version matching your
  PHP version 5.6.xx.x

In the composer.json I see the the minimal requirement for this package is PHP 7.x.x

Why is requirement set while php 5.6 is not EOL?

**Comment by sebastiandedeyne** [comment]
We haven't been supporting 5.6 for a while because all of our new projects use PHP7+, which is going to be the standard sooner than later.

For a more nuanced response, we have a blog post on the subject: https://murze.be/2016/01/why-we-are-requiring-php-7-for-our-new-packages/
