### ISSUE TITLE
Laravel-varnish in combination with laravel-responsecache

### ISSUE THREAD

**Issue by alvinbakker** [spatie/laravel-varnish#16]
This is not an issue, but a question... Is it feasable to use laravel-responsecache in combination with laravel-varnish? Or is it better to use one of them? And if I have to choose, which one is better?

**Comment by freekmurze** [comment]
I'd only use one of them at the same time. Response cache is easy to install and will speed up your app. Varnish is harder to set up (you need to have some system administration knowledge), but it can get you response times of 40ms and lower.
