### ISSUE TITLE
How to configure behind https 

### ISSUE THREAD

**Issue by mikimaine** [spatie/laravel-varnish#17]
How can we configure this package when varnish is behind SSL.

**Comment by freekmurze** [comment]
Varnish doesn't understand ssl or http2. So you need to put a webserver in front of which will strip off the https part and proxies it to Varnish.

If you're using nginx you could add something to your config file in the lines of:

```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name yourdomain.com;

    ssl_certificate /etc/nginx/ssl/yourdomain.com/server.crt;
    ssl_certificate_key /etc/nginx/ssl/yourdomain.com/server.key;

    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
    ssl_prefer_server_ciphers on;
    ssl_dhparam /etc/nginx/dhparams.pem;
    
    if ($request_uri ~* "^(.*/)index\.php/?(.*)") {
       return 301 "$1$2";
    }
    
    location / {
        proxy_pass http://127.0.0.1:80;
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header Host $host;
    }
}
```

I'm planning to write a blogpost with more info on my blog https://murze.be so keep an eye on that. If you need more info now, I suggest you Google a bit around a lot of people have come across the same problem and were able to solve it.

**Comment by maxxscho** [comment]
@freekmurze did you write an article about this topic? Didn't find anything on your blog. 
I'm currently facing the same problem with Varnish on Forge behind https. I tinkered around trying to combine your example and some code snippets found via google and I couldn't get it to work correct. The best result was my browser making two requests, the initial on https and than another on http. I don't know if this is common with this "proxy-server". The other problem was form submissions stopped working.
Do have any recommended resources? I'm already searching for days…
