### ISSUE TITLE
How to deal with non-cacheable XHR requests?

### ISSUE THREAD

**Issue by qodeboy** [spatie/laravel-varnish#23]
Hello,

I'm trying to integrate this package and Varnish on my project. The package itself is working fine, but there is one more general issue I hope you can help with.

Any AJAX request to an non-cacheable API will set cookie, even if controller itself doesn't explicitly use session. This results in all subsequent requests for visitor will bypass cache.

Is there a way to tell Laravel to set cookie on when it's actually needed?

So more generalized question is: is there a way to mix cacheable and non-cacheable requests fro same visitor?

**Comment by freekmurze** [comment]
Not certain, but I don't think that's possible. 

I suggest you open up an issue about this on the Laravel repo.
