### ISSUE TITLE
Lumen supported?

### ISSUE THREAD

**Issue by Yorgovan** [spatie/laravel-varnish#26]
Can this work on Lumen also?

I installed it, set `$app->register(Spatie\Varnish\VarnishServiceProvider::class);` in `app.php` and tried to publish config file but it returns `  Call to undefined function Spatie\Varnish\config_path()  `

**Comment by freekmurze** [comment]
I'm not a Lumen user, so I haven't researched how to get it up and running in Lumen.

**Comment by pxgamer** [comment]
Looks like `config_path()` is a [Laravel-only function][Laravel].

[Laravel]: https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/helpers.php#L276

**Comment by Yorgovan** [comment]
I did make it work using these:
[config_path function for Lumen framework](https://gist.github.com/mabasic/21d13eab12462e596120)
https://github.com/laravelista/lumen-vendor-publish
