### ISSUE TITLE
Remote Varnish purge support

### ISSUE THREAD

**Issue by thim81** [spatie/laravel-varnish#27]
Hi @freekmurze 

At delta.blue (belgian cloud platform), we suggest your Laravel-Varnish package to all our customers make their Laravel sites fly.

Currently the package uses the `varnishadm` to clear the cache.
This works fine when the laravel site is hosted on the same server as the Varnish, but with the current cloud platforms and containerization, this will become less the use-case.

To solve this, we would to suggest an addition to this package:

1. Provide a authenticated purge / ban support for remote Varnish servers via TCP (https://varnish-cache.org/docs/trunk/reference/varnish-cli.html#authentication-with-s)

2. Extend the `php artisan varnish:flush` to support this method

3. a VCL snippet to be able to do this TCP ban/purge

What do you think?

If this would be OK, we would add the code and push a PR for approval?

**Comment by freekmurze** [comment]
Sure, send a well tested PR with an updated readme. If the code is simple enought it'll get merged.
