### ISSUE TITLE
Ban specific uri

### ISSUE THREAD

**Issue by tomadmiraal** [spatie/laravel-varnish#29]
Is it posible to Ban/Purge/Flush a specific URI or pattern?

for our project its not really an option to flush the whole cache. we run multiple news platforms on one application with dynamic content. We fragmented the content by using ESI. this is pretty useless when I only can flush the whole cache.

wouldn't it be nice to be able to do something like:

(new Spatie\Varnish\Varnish())->pattern('domain.com/uri/to/ban')->flush();

or maybe the option to list more then one pattern?

**Comment by freekmurze** [comment]
I'd accept fully tested PRs that add extra functionality to the package.
