### ISSUE TITLE
Remove sudo requirement

### ISSUE THREAD

**Issue by danmichaelo** [spatie/laravel-varnish#32]
https://github.com/spatie/laravel-varnish/blob/master/src/Varnish.php#L50

There are many options for running varnishadm without sudo, such as giving a group read access to the secret file: https://book.varnish-software.com/4.0/chapters/Getting_Started.html#the-front-end-varnishadm-of-the-varnish-command-line-interface-cli

My suggestion is to make the varnishadm command a configuration option, which defaults to "varnishadm". Users who prefer sudo can change it to "sudo varnishadm" or to the full path of varnishadm or anything.

**Comment by freekmurze** [comment]
If this can be achieved in a simple, non breaking way I'd accept a PR for this.
