### ISSUE TITLE
csrf-token

### ISSUE THREAD

**Issue by agborkowski** [spatie/laravel-varnish#39]
how laravel-varnish deal with csrf-token build in laravel ?

i see when csrf is on, laravel send headers response with: cache-control: no-cache, private

and inside the template there we have meta name tag:

`
<meta name="csrf-token" content="5kWRKMPuOUS8v7fW3gSUiPMBdAz3UiJSA8SBmKnd">
`

**Comment by freekmurze** [comment]
Our package itself doesn't handle this. You should configure Varnish itself to make this work. Take a look at ESI.

https://www.fastly.com/blog/caching-uncacheable-csrf-security

**Comment by Nuranto** [comment]
That solution won't work. The csrf will be updated with an ESI block, ok.
But the cookie, and so the session won't start before your post, so your csrf won't be accurate.
I did not find any solution to this. Did you @agborkowski  ?
Of course, we could disable cache on form pages, but in some cases, there is a form on footer (so every pages :/)
