### ISSUE TITLE
Purge not working

### ISSUE THREAD

**Issue by norotico** [spatie/laravel-varnish#46]
I'm using Laravel 8 and Docker.

Trying to purge as in the docs `(new Varnish())->flush()` gives me "expected array, string given" on Spatie\Varnish\Varnish:66.

Which is probably easily fixed by changing it to `$process = new Process([$command]);`.

But the real issue is that since Varnish is installed on its own container, its commands can't be found.

Is there an alternative that doesn't involve multiple Varnish installations?

**Comment by tomvo** [comment]
@norotico i'm experiencing the same, it will be tricky to solve this in the way it works now. By ways of calling `sudo varnishadm`.

I think a better implementation would be to use HTTP purge commands to handle the purging to your varnish cache but i think that's outside of the scope of this library. See also: https://github.com/spatie/laravel-varnish/issues/27

**Comment by mayhemant** [comment]
I'm facing the same

![image](https://user-images.githubusercontent.com/74244707/102894984-eea60c80-4489-11eb-8fb4-b6f2866e0380.png)
