### ISSUE TITLE
Why not s-maxage?

### ISSUE THREAD

**Issue by dvershinin** [spatie/laravel-varnish#53]
Disclaimer: I haven't used the package, but merely checked its code [here](https://github.com/spatie/laravel-varnish/blob/2.8.2/src/Middleware/CacheWithVarnish.php#L15).

You're using `max-age`, however, this dictates caching policy to both Varnish and browsers.

It makes much more sense to use `s-maxage`  for Varnish cache policy, as it fully supports it.

Why: in a typical scenario, when you make something cacheable on Varnish for a long time, you *don't* want to
have it cached for a long time in clients. You configure something like `s-maxage=<high>, max-age=0` and PURGE content in Varnish upon updates (e.g. in admin).  In that way, clients benefit from Varnish caching without seeing stale data.

**Comment by fhferreira** [comment]
+1 @freekmurze ?
