### ISSUE TITLE
The mentioned blog post link is not working

### ISSUE THREAD

**Issue by devansh-webkul** [spatie/laravel-varnish#58]
## Minor Info
- Mentioned blog post link in the installation section is not working,
https://github.com/spatie/laravel-varnish#installation

- Target line,
https://github.com/spatie/laravel-varnish/blob/914d22b26cb8d84bb6cc6892b0d3b640cb3432f3/README.md?plain=1#L22

**Comment by freekmurze** [comment]
Fixed
